// 通用 ===========================================================
export const GET_CATEGORY_TREE_SUCCESS = 'GET_CATEGORY_TREE_SUCCESS'
export const GET_CATEGORY_TREE_ERROR = 'GET_CATEGORY_TREE_ERROR'
export const GET_DOMAIN_CONFIG_SUCCESS = 'GET_DOMAIN_CONFIG_SUCCESS'
export const GET_DOMAIN_CONFIG_ERROR = 'GET_DOMAIN_CONFIG_ERROR'

// 登录相关 =========================================================
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const LOAD_USERINFO = 'LOAD_USERINFO'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_ERROR = 'GET_USERINFO_ERROR'
export const SET_USER_INFO = 'SET_USER_INFO'
// 任务相关 =========================================================
export const GET_TASK_LIST_SUCCESS = 'GET_TASK_LIST_SUCCESS'
export const GET_TASK_LIST_ERROR = 'GET_TASK_LIST_ERROR'
export const GET_USERTASK_LIST_SUCCESS = 'GET_USERTASK_LIST_SUCCESS'
export const GET_USERTASK_LIST_ERROR = 'GET_USERTASK_LIST_ERROR'
export const GET_TASK_DETAIL_SUCCESS = 'GET_TASK_DETAIL_SUCCESS'
export const GET_TASK_DETAIL_ERROR = 'GET_TASK_DETAIL_ERROR'
export const GET_TASK_USER_LIST_SUCCESS = 'GET_TASK_USER_LIST_SUCCESS'
export const GET_TASK_USER_LIST_ERROR = 'GET_TASK_USER_LIST_ERROR'

// 消息相关 =========================================================
export const GET_MESSAGE_ITEM_SUCCESS = 'GET_MESSAGE_ITEM_SUCCESS'
export const GET_MESSAGE_ITEM_ERROR = 'GET_MESSAGE_ITEM_ERROR'
export const GET_MESSAGE_LIST_SUCCESS = 'GET_MESSAGE_LIST_SUCCESS'
export const GET_MESSAGE_LIST_ERROR = 'GET_MESSAGE_LIST_ERROR'
export const GET_MESSAGE_DETAIL_SUCCESS = 'GET_MESSAGE_DETAIL_SUCCESS'
export const GET_MESSAGE_DETAIL_ERROR = 'GET_MESSAGE_DETAIL_ERROR'
export const GET_MESSAGE_COUNT_SUCCESS = 'GET_MESSAGE_COUNT_SUCCESS'
export const GET_MESSAGE_COUNT_ERROR = 'GET_MESSAGE_COUNT_ERROR'

export const GET_AUDIT_SUCCESS = 'GET_AUDIT_SUCCESS'

export const SET_BANK_POST = 'SET_BANK_POST'
